In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset=pd.read_csv("advertising.csv")

In [4]:
dataset

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [5]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [7]:
print(x)

[[230.1  37.8  69.2]
 [ 44.5  39.3  45.1]
 [ 17.2  45.9  69.3]
 [151.5  41.3  58.5]
 [180.8  10.8  58.4]
 [  8.7  48.9  75. ]
 [ 57.5  32.8  23.5]
 [120.2  19.6  11.6]
 [  8.6   2.1   1. ]
 [199.8   2.6  21.2]
 [ 66.1   5.8  24.2]
 [214.7  24.    4. ]
 [ 23.8  35.1  65.9]
 [ 97.5   7.6   7.2]
 [204.1  32.9  46. ]
 [195.4  47.7  52.9]
 [ 67.8  36.6 114. ]
 [281.4  39.6  55.8]
 [ 69.2  20.5  18.3]
 [147.3  23.9  19.1]
 [218.4  27.7  53.4]
 [237.4   5.1  23.5]
 [ 13.2  15.9  49.6]
 [228.3  16.9  26.2]
 [ 62.3  12.6  18.3]
 [262.9   3.5  19.5]
 [142.9  29.3  12.6]
 [240.1  16.7  22.9]
 [248.8  27.1  22.9]
 [ 70.6  16.   40.8]
 [292.9  28.3  43.2]
 [112.9  17.4  38.6]
 [ 97.2   1.5  30. ]
 [265.6  20.    0.3]
 [ 95.7   1.4   7.4]
 [290.7   4.1   8.5]
 [266.9  43.8   5. ]
 [ 74.7  49.4  45.7]
 [ 43.1  26.7  35.1]
 [228.   37.7  32. ]
 [202.5  22.3  31.6]
 [177.   33.4  38.7]
 [293.6  27.7   1.8]
 [206.9   8.4  26.4]
 [ 25.1  25.7  43.3]
 [175.1  22.5  31.5]
 [ 89.7   9.9  35.7]
 [239.9  41.5

In [8]:
print(y)

[22.1 10.4 12.  16.5 17.9  7.2 11.8 13.2  4.8 15.6 12.6 17.4  9.2 13.7
 19.  22.4 12.5 24.4 11.3 14.6 18.  17.5  5.6 20.5  9.7 17.  15.  20.9
 18.9 10.5 21.4 11.9 13.2 17.4 11.9 17.8 25.4 14.7 10.1 21.5 16.6 17.1
 20.7 17.9  8.5 16.1 10.6 23.2 19.8  9.7 16.4 10.7 22.6 21.2 20.2 23.7
  5.5 13.2 23.8 18.4  8.1 24.2 20.7 14.  16.  11.3 11.  13.4 18.9 22.3
 18.3 12.4  8.8 11.  17.   8.7  6.9 14.2  5.3 11.  11.8 17.3 11.3 13.6
 21.7 20.2 12.  16.  12.9 16.7 14.   7.3 19.4 22.2 11.5 16.9 16.7 20.5
 25.4 17.2 16.7 23.8 19.8 19.7 20.7 15.   7.2 12.   5.3 19.8 18.4 21.8
 17.1 20.9 14.6 12.6 12.2  9.4 15.9  6.6 15.5  7.  16.6 15.2 19.7 10.6
  6.6 11.9 24.7  9.7  1.6 17.7  5.7 19.6 10.8 11.6  9.5 20.8  9.6 20.7
 10.9 19.2 20.1 10.4 12.3 10.3 18.2 25.4 10.9 10.1 16.1 11.6 16.6 16.
 20.6  3.2 15.3 10.1  7.3 12.9 16.4 13.3 19.9 18.  11.9 16.9  8.  17.2
 17.1 20.   8.4 17.5  7.6 16.7 16.5 27.  20.2 16.7 16.8 17.6 15.5 17.2
  8.7 26.2 17.6 22.6 10.3 17.3 20.9  6.7 10.8 11.9  5.9 19.6 17.3  7.6
 14.  1

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

In [11]:
x_test

array([[ 69.2,  20.5,  18.3],
       [ 50. ,  11.6,  18.4],
       [ 90.4,   0.3,  23.2],
       [289.7,  42.3,  51.2],
       [170.2,   7.8,  35.2],
       [ 56.2,   5.7,  29.7],
       [  8.7,  48.9,  75. ],
       [240.1,   7.3,   8.7],
       [ 23.8,  35.1,  65.9],
       [197.6,  23.3,  14.2],
       [261.3,  42.7,  54.7],
       [ 87.2,  11.8,  25.9],
       [156.6,   2.6,   8.3],
       [187.8,  21.1,   9.5],
       [ 76.4,  26.7,  22.3],
       [120.2,  19.6,  11.6],
       [265.6,  20. ,   0.3],
       [  0.7,  39.6,   8.7],
       [ 74.7,  49.4,  45.7],
       [213.4,  24.6,  13.1],
       [287.6,  43. ,  71.8],
       [140.3,   1.9,   9. ],
       [175.1,  22.5,  31.5],
       [131.7,  18.4,  34.6],
       [ 53.5,   2. ,  21.4],
       [123.1,  34.6,  12.4],
       [165.6,  10. ,  17.6],
       [205. ,  45.1,  19.6],
       [224. ,   2.4,  15.6],
       [ 25.1,  25.7,  43.3],
       [ 67.8,  36.6, 114. ],
       [198.9,  49.4,  60. ],
       [280.7,  13.9,  37. ],
       [24

In [12]:
y_test

array([11.3,  8.4, 12. , 25.4, 16.7,  8.7,  7.2, 18.2,  9.2, 16.6, 24.2,
       10.6, 15.5, 20.6, 11.8, 13.2, 17.4,  1.6, 14.7, 17. , 26.2, 10.3,
       16.1, 12.9,  8.1, 15.2, 17.6, 22.6, 16.6,  8.5, 12.5, 23.7, 16.1,
       21.8,  5.6,  6.7,  9.7, 17.9, 13.6,  7.2, 10.8, 11. , 15. , 20.9,
       17.1, 14. ,  4.8,  8.7, 15.9, 10.4, 12.4, 19.7, 17.6, 20.5, 10.1,
        9.7, 21.4, 16.4, 16.6,  5.5])

In [13]:
x_train

array([[265.2,   2.9,  43. ],
       [197.6,   3.5,   5.9],
       [218.5,   5.4,  27.4],
       [147.3,  23.9,  19.1],
       [171.3,  39.7,  37.7],
       [217.7,  33.5,  59. ],
       [262.7,  28.8,  15.9],
       [163.5,  36.8,   7.4],
       [100.4,   9.6,   3.6],
       [ 76.3,  27.5,  16. ],
       [184.9,  43.9,   1.7],
       [134.3,   4.9,   9.3],
       [273.7,  28.9,  59.7],
       [296.4,  36.3, 100.9],
       [ 96.2,  14.8,  38.9],
       [109.8,  47.8,  51.4],
       [255.4,  26.9,   5.5],
       [204.1,  32.9,  46. ],
       [240.1,  16.7,  22.9],
       [193.7,  35.4,  75.6],
       [191.1,  28.7,  18.2],
       [ 89.7,   9.9,  35.7],
       [ 43. ,  25.9,  20.5],
       [ 38.2,   3.7,  13.8],
       [ 13.1,   0.4,  25.6],
       [239.3,  15.5,  27.3],
       [ 17.2,  45.9,  69.3],
       [210.7,  29.5,   9.3],
       [ 25.6,  39. ,   9.3],
       [177. ,   9.3,   6.4],
       [206.9,   8.4,  26.4],
       [ 66.1,   5.8,  24.2],
       [149.7,  35.6,   6. ],
       [12

In [14]:
y_train

array([17.7, 16.7, 17.2, 14.6, 16. , 19.4, 20.2, 18. , 10.7, 12. , 20.7,
       14. , 20.8, 23.8, 12.3, 16.7, 19.8, 19. , 20.9, 19.2, 17.3, 10.6,
        9.6,  7.6,  5.3, 20.7, 12. , 18.4,  9.5, 14.8, 17.9, 12.6, 17.3,
       11. , 14. , 16.8, 27. ,  6.6, 22.2, 17.1,  7.3, 11.9, 16.4, 22.1,
       11.5, 18.4, 16.9, 16. , 17.2, 17.1, 22.3,  9.7, 19.8, 20.2, 13.7,
       13.3, 20.5, 10.3, 11.6, 18. , 22.4,  5.3, 20.7, 22.6, 16.7,  6.9,
       16.5, 12.2, 11.9, 25.5, 11.8, 18.9, 21.7,  7. ,  3.2, 17.5, 15.3,
        7.3, 18.4, 17.4,  6.6, 19.8, 17.8, 13.2, 11.3, 10.4, 15.5, 19.9,
       20.7, 15. ,  5.7, 16.7, 24.4, 10.1, 19.6, 21.2, 10.1, 24.7, 11.9,
       18.9, 14.6, 11.6, 11.9,  8. , 11.9, 20.2, 13.2, 20.1, 20. , 25.4,
       10.5, 17.2, 11.3, 11. , 12.6, 10.9, 19.6,  8.8, 14.2, 17. , 16.9,
       17.3, 20.9, 16.5, 10.8, 21.5, 23.8, 10.9, 12.9, 18.3, 16. , 25.4,
       17.5, 15.6, 19.7, 13.4,  5.9,  9.4, 23.2,  7.6])

In [16]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [17]:
y_pred=regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[10.69 11.3 ]
 [ 8.67  8.4 ]
 [ 9.6  12.  ]
 [25.   25.4 ]
 [14.74 16.7 ]
 [ 8.38  8.7 ]
 [10.7   7.2 ]
 [18.38 18.2 ]
 [ 9.97  9.2 ]
 [17.88 16.6 ]
 [23.53 24.2 ]
 [10.71 10.6 ]
 [13.38 15.5 ]
 [17.1  20.6 ]
 [11.77 11.8 ]
 [13.31 13.2 ]
 [21.13 17.4 ]
 [ 9.11  1.6 ]
 [14.24 14.7 ]
 [18.87 17.  ]
 [25.01 26.2 ]
 [12.43 10.3 ]
 [16.62 16.1 ]
 [13.84 12.9 ]
 [ 7.8   8.1 ]
 [15.13 15.2 ]
 [14.7  17.6 ]
 [20.7  22.6 ]
 [16.98 16.6 ]
 [ 8.95  8.5 ]
 [12.59 12.5 ]
 [20.93 23.7 ]
 [21.34 16.1 ]
 [21.89 21.8 ]
 [ 7.24  5.6 ]
 [ 7.06  6.7 ]
 [ 9.28  9.7 ]
 [15.68 17.9 ]
 [13.34 13.6 ]
 [ 7.29  7.2 ]
 [11.06 10.8 ]
 [ 9.09 11.  ]
 [15.61 15.  ]
 [18.22 20.9 ]
 [18.96 17.1 ]
 [13.47 14.  ]
 [ 5.37  4.8 ]
 [10.6   8.7 ]
 [15.66 15.9 ]
 [10.98 10.4 ]
 [12.21 12.4 ]
 [20.71 19.7 ]
 [20.71 17.6 ]
 [16.96 20.5 ]
 [ 9.97 10.1 ]
 [ 9.44  9.7 ]
 [23.61 21.4 ]
 [15.99 16.4 ]
 [18.07 16.6 ]
 [ 8.26  5.5 ]]
